# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DocumentCreator
                                 A QGIS plugin
 Create docx or odt document for selected object
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-10
        copyright            : (C) 2018 by 1
        email                : 2
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DocumentCreator class from file DocumentCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .document_creator import DocumentCreator
    return DocumentCreator(iface)
